version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=local"
  microservice.host.api:
    image: microservice-host-api
    build:
      context: .
      dockerfile: src/Heimdall.Templates.DotNet.Microservice.Host.Api/Dockerfile
  microservice.host.worker:
    image: microservice-host-worker
    build:
      context: .
      dockerfile: src/Heimdall.Templates.DotNet.Microservice.Host.Worker/Dockerfile